/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *hseparator1;
  GtkWidget *scrolledwindow1,*scrolledwindow2,*scrolledwindow3;
  GtkWidget *textview1;
  GtkWidget *section;
  GtkWidget *symbol;
  GtkWidget *readELF;
  GtkWidget *start;
  GtkWidget *quit;
  GtkWidget *filechooserbutton1;
  GtkWidget *param;
  GtkWidget *parameters;
  GtkTooltips *tooltips;
  GtkTextBuffer *buffer;
  GtkWidget *treeview1,*treeview2,*treeview3;
  GtkWidget *statusbar1,*statusbar2,*statusbar3;
  GtkListStore *store1,*store2,*store3;
  GtkTreeSelection *selection;
  GtkTreeIter iter1,iter2,iter3;
  GtkTreeViewColumn *column,*column2,*column3,*columnid3;
  GtkCellRenderer *renderer,*renderer2,*renderer3;
  GtkWidget *vbox1, *hbox1, *hbox2,*hbox3,*hbox4,*hbox5,*hbox6,*hbox7;
  gint context_id1,context_id2,context_id3;
 
  GtkWidget *treeview4,*treeview5,*treeview6;
  GtkWidget *statusbar4,*statusbar5,*statusbar6;
  GtkListStore *store4,*store5,*store6;
  GtkTreeIter iter4,iter5,iter6;
  GtkTreeViewColumn *column4,*columnid4,*column5,*columnid5,*column6,*columnid6;
  GtkCellRenderer *renderer4,*renderer5,*renderer6;
  GtkWidget *hbox8, *hbox9,*hbox10,*hbox11,*hbox12,*hbox13;
  guint context_id4,context_id5,context_id6;
  GtkWidget *scrolledwindow4,*scrolledwindow5,*scrolledwindow6;

  GtkWidget* create_window1 (void);
